name: Test Labels

on:
  pull_request:
    types: [labeled]

env:
  message: 'World'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Init single-line script
        run: echo Hello, $(message}!